# Generated by Django 4.1 on 2022-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=12, null=True)),
                ('meaning', models.CharField(max_length=12, null=True)),
                ('story', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
